[mongodb]
localhost

[redis]
redis.daws86s.co.in

[mysql]
mysql.daws86s.co.in

[rabbitmq]
rabbitmq.daws86s.co.in

[catalogue]
catalogue.daws86s.co.in

[cart]
cart.daws86s.co.in

[user]
user.daws86s.co.in

[shipping]
shipping.daws86s.co.in

[payment]
payment.daws86s.co.in

[frontend]
frontend.daws86s.co.in

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar